name: Build Crystal (aarch64-unknown-linux-gnu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
#  schedule:
#    - cron: '0 3 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.set.outputs.should }}
    steps:
      - uses: actions/checkout@v3
      - name: Latest crystal version (Remote)
        run: echo "CRYSTAL_LATEST=$(git ls-remote --tags https://github.com/crystal-lang/crystal.git | grep -o 'refs/tags/[0-9]*\.[0-9]*\.[0-9]*' | sort -r | head -n 1 | grep -o '[^\/]*$')" >> $GITHUB_ENV
      - name: Latest crystal version (Built)
        run: echo "CRYSTAL_BUILT_LATEST=$(curl -fsSL https://github.com/crow-rest/crystal-aarch64-linux-builds/releases/download/track/crystal-version)" >> $GITHUB_ENV
      - name: Set Output
        id: set
        run: echo "should=${{ (env.CRYSTAL_LATEST != env.CRYSTAL_BUILT_LATEST) || (github.event_name == 'pull_request') }}" >> $GITHUB_OUTPUT
      - name: Print
        run: echo ${{ steps.set.outputs.should }}

  build:
    runs-on: ubuntu-latest
    needs: [ check ]
    if: ${{ needs.check.outputs.should-build }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            crystal
            bdwgc
          key: ${{ runner.os }}-crystal-build-${{ env.CRYSTAL_LATEST }}-${{ secrets.REBUILD }}

      - name: Install pkgs
        run: sudo apt update && sudo apt-get install -y libbsd-dev libedit-dev libevent-dev libgmp-dev libgmpxx4ldbl 
          libpcre3-dev libssl-dev libtool libxml2-dev libyaml-dev libz-dev
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.6.1
        with:
          version: 14
      - name: Install crystal
        run: curl -fsSL https://crystal-lang.org/install.sh | sudo bash
      - name: Clone repos
        run: |
          git -C bdwgc fetch || git clone https://github.com/ivmai/bdwgc.git bdwgc
          git -C crystal fetch || git clone https://github.com/crystal-lang/crystal.git crystal

      - name: Make bdwgc latest tag
        working-directory: ./bdwgc
        run: git checkout $(git describe --tags --abbrev=0)
      - name: Get bdwgc deps
        working-directory: ./bdwgc
        run: git -C libatomic_ops pull origin master || git clone https://github.com/ivmai/libatomic_ops.git
      - name: Build and install bdwgc
        working-directory: ./bdwgc
        run: |
          [ -f Makefile ] && make clean
          autoreconf -vif
          ./configure --enable-static --disable-shared
          make -j
          make check
          sudo make install

      - name: Make crystal latest tag
        working-directory: ./crystal
        run: git checkout $(git describe --tags --abbrev=0)
      - name: Build crystal
        working-directory: ./crystal
        run: |
          make clean
          make crystal verbose=1

      - name: Build aarch64-unknown-linux-gnu object file
        working-directory: ./crystal
        run: ./bin/crystal build src/compiler/crystal.cr --cross-compile --target=aarch64-linux-gnu -D without_openssl -D without_zlib --release --verbose
      - name: Store aarch64-unknown-linux-gnu object file
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-unknown-linux-gnu
          path: crystal/crystal.o

  aarch64-unknown-linux-gnu:
    strategy:
      fail-fast: false
      matrix:
        target: [ aarch64-unknown-linux-gnu ]
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Read
        run: echo TEST
