name: Build Crystal (aarch64-unknown-linux-gnu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
#  schedule:
#    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            crystal
            bdwgc
#            .crystal-latest-tag
#            .bdwgc-latest-tag
          key: ${{ runner.os }}-crystal-build
#      - name: Make sure files exist
#        run: |
#          touch .crystal-latest-tag
#          touch .bdwgc-latest-tag
      - name: Install pkgs
        run: sudo apt update && sudo apt-get install -y libbsd-dev libedit-dev libevent-dev libgmp-dev libgmpxx4ldbl 
          libpcre3-dev libssl-dev libtool libxml2-dev libyaml-dev libz-dev
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.6.1
        with:
          force-version: 14.0.6
      - name: Install crystal
        run: curl -fsSL https://crystal-lang.org/install.sh | sudo bash
      - name: Clone repos
        run: |
          git -C bdwgc fetch || git clone https://github.com/ivmai/bdwgc.git bdwgc
          git -C crystal fetch || git clone https://github.com/crystal-lang/crystal.git crystal

      - name: Make bdwgc latest tag
        working-directory: ./bdwgc
        run: |
          git fetch
          git checkout $(git describe --tags --abbrev=0)
      - name: Get bdwgc deps
        working-directory: ./bdwgc
        run: git clone https://github.com/ivmai/libatomic_ops.git 2> /dev/null
      - name: Build and install bdwgc
        working-directory: ./bdwgc
        run: |
          make clean
          autoreconf -vif
          ./configure --enable-static --disable-shared
          make -j
          make check
          sudo make install

      - name: Make crystal latest tag
        working-directory: ./crystal
        run: |
          git fetch
          git checkout $(git describe --tags --abbrev=0)
      - name: Build and test crystal
        working-directory: ./crystal
        run: |
          make clean
          make crystal
          make std_spec compiler_spec

      - name: Build aarch64-unknown-linux-gnu object file
        working-directory: ./crystal
        run: ./bin/crystal build src/compiler/crystal.cr --cross-compile --target=aarch64-linux-gnu -D without_openssl -D without_zlib --release

      - name: LS
        working-directory: ./crystal
        run: |
          ls
          ls build
